### ISSUE TITLE
Error on launching: Could not load file or assembly 'Microsoft.Xrm.Sdk, Version=7.0.0.0

### ISSUE THREAD

**Issue by goodmorningsky** [andypopkin/XrmToolBox---Bulk-Workflow-Execution#1]
Steps
a. downloaded XrmToolBox v1.2016.5.27 
b. Install Selected package from Plugin Store
Bulk Workflow Execution version 1.2016.5.17
c. connect to CRM 2016
d. Run 'Bulk Workflow Execution'
e. Error "Could not load file or assembly 'Microsoft.Xrm.Sdk, Version =7.0.0.0, .."

(I tried various way to resolve it, but failed. I don't know where the version 7 info comes from..)

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xrm.Sdk, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Xrm.Sdk, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at XrmToolBox___Bulk_Workflow_Execution.BulkWorkflowExecution.<getWorkflows>b__4(BackgroundWorker w, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by andypopkin** [comment]
I have updated the plugin in the plugin store to resolve this issue. Please upgrade and let me know if that does not work for you.
