### ISSUE TITLE
The Executing will stop with no errors

### ISSUE THREAD

**Issue by aboodh95** [andypopkin/XrmToolBox---Bulk-Workflow-Execution#5]
Hi

Recently the execution of the workflows will stop without any error message and the loading panel will disappear also the window will remain disabled

**Comment by andypopkin** [comment]
@aboodh95 are you still seeing this issue? Anything specific cause it?

**Comment by aboodh95** [comment]
No, i'm sorry i suppose to close this issue but i think it's fixed

Thank you
