### ISSUE TITLE
All on-demand workflows are not loading

### ISSUE THREAD

**Issue by jessdutoit** [andypopkin/XrmToolBox---Bulk-Workflow-Execution#6]
Hi there.

When i connect to my org and load the list of workflows, all my on demand worflows are not loading.
Am I missing something?

**Comment by andypopkin** [comment]
Hi @jessdutoit - apologies for the late reply. Are you still having this issue?

**Comment by nevinAnderson** [comment]
I am having this problem today.  :)  The workflows I am looking for are on Quote and Order entity and are marked to be run on-demand.  They are just not showing up after reconnecting to the org, restarting XRM Toolbox, using Bulk Workflow Execution to refresh the listed workflows.   There are several workflows showing up in the list and they are consistent, but the ones I seek are missing from the list.

**Comment by andypopkin** [comment]
Are other on-demand workflows appearing for other entities?

**Comment by nevinAnderson** [comment]
Andy, thank you for your reply.

Yes, other workflows do appear.

**Comment by andypopkin** [comment]
Is this still an issue for you?

**Comment by nevinAnderson** [comment]
I think I got it sorted out and it was user error (wrong org). Thank you!

Best Regards,

Nevin Anderson
m 801.425.3995 | nevin.anderson@journeyteam.com<mailto:nevin.anderson@journeyteam.com>
[JT Logo]
